spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/rmontero/Repos/microservices-ecommerce/config-data
          clone-on-start: true
          default-label: main
server:
  port: 8888
